/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import {
  Theme,
} from './global/interfaces';

declare global {

  namespace StencilComponents {
    interface WopPatternLock {
      'generateGrid': (rows: number, cols: number) => void;
      'height': number;
      'intervalTime': number;
      'playPattern': (nodes: any[]) => void;
      'setTheme': (theme: Theme) => void;
      'start': () => void;
      'stopPattern': (emit?: boolean) => void;
      'width': number;
    }
  }

  interface HTMLWopPatternLockElement extends StencilComponents.WopPatternLock, HTMLStencilElement {}

  var HTMLWopPatternLockElement: {
    prototype: HTMLWopPatternLockElement;
    new (): HTMLWopPatternLockElement;
  };
  interface HTMLElementTagNameMap {
    'wop-pattern-lock': HTMLWopPatternLockElement;
  }
  interface ElementTagNameMap {
    'wop-pattern-lock': HTMLWopPatternLockElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'wop-pattern-lock': JSXElements.WopPatternLockAttributes;
    }
  }
  namespace JSXElements {
    export interface WopPatternLockAttributes extends HTMLAttributes {
      'height'?: number;
      'intervalTime'?: number;
      'onPatternLock:patternCompleted'?: (event: CustomEvent) => void;
      'onPatternLock:patternPlayed'?: (event: CustomEvent) => void;
      'width'?: number;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
